version: '3.9'

services:  
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    command: sh -c "
      python business_manage/manage.py makemigrations && 
      python business_manage/manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 business_manage.wsgi:application
      "
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env

  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - django_db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

volumes:
  django_db:
